# Generated by Django 4.0.5 on 2022-10-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='booking_notes',
            new_name='product_notes',
        ),
    ]
