# Generated by Django 4.0.5 on 2022-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='notes',
            new_name='booking_notes',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='booking_status',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='is_damaged',
            new_name='is_container_damaged',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_damaged',
            new_name='is_product_damaged',
        ),
        migrations.AddField(
            model_name='container',
            name='container_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='booking_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
