# Generated by Django 4.0.5 on 2022-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(-1, 'ERROR'), (0, 'XX'), (1, 'PENDING'), (2, 'COMPLETE'), (3, 'CLOSED')], default=0),
        ),
    ]
